/*
 * \file config.h
 * This file is part of LyX, the document processor.
 * Licence details can be found in the file COPYING.
 *
 * This is the compilation configuration file for LyX.
 * It was generated by cmake.
 * You might want to change some of the defaults if something goes wrong
 * during the compilation.
 */

#ifndef _CONFIG_H
#define _CONFIG_H


#ifndef	INCLUDE_ORIGINAL
/* this is actually defined in gettext.h - TNick */
#define N_(t) t
#define _(t) docstring()
#endif	// INCLUDE_ORIGINAL


// obligatory flags
#define QT_NO_STL 1
#define QT_NO_KEYWORDS 1
#define HAVE_ICONV 1

#include "configCompiler.h"

#ifdef LYX_ENABLE_PCH
#include "pcheaders.h"
#endif


#define PACKAGE "lyx2.1"
#define PACKAGE_VERSION "2.1.0svn"
#define PACKAGE_STRING "LyX 2.1.0svn"
#define PACKAGE_BUGREPORT "lyx-devel@lists.lyx.org"
#define LYX_DATE "2011-04-29"
#define VERSION_INFO "CMake Build"
#define LYX_DIR_VER "LYX_DIR_21x"
#define LYX_USERDIR_VER "LYX_USERDIR_21x"
#define LYX_MAJOR_VERSION 2
#define LYX_MINOR_VERSION 1

#define PROGRAM_SUFFIX "2.1"
#define LYX_ABS_INSTALLED_DATADIR "/usr/local/lyx2.1"
#define LYX_ABS_INSTALLED_LOCALEDIR "/usr/local/lyx2.1/locale"
#define LYX_ABS_TOP_SRCDIR "/media/data/trunks/lyx/src-trunk"

#define USE_POSIX_PACKAGING 1
/* #undef USE_WINDOWS_PACKAGING */
/* #undef USE_MACOSX_PACKAGING */
/* #undef PATH_MAX */

/* #undef WORDS_BIGENDIAN */

/* #undef LYX_MERGE_FILES */

#define LYX_USE_TR1 1
/* #undef LYX_USE_TR1_REGEX */

/* #undef ASPELL_FOUND */
#ifdef ASPELL_FOUND
#define USE_ASPELL 1
#endif

/* #undef AIKSAURUSLIB_FOUND */
#ifdef AIKSAURUSLIB_FOUND
#define HAVE_LIBAIKSAURUS 1
#define AIKSAURUS_H_LOCATION ""
#endif

/* #undef ENCHANT_FOUND */
#ifdef ENCHANT_FOUND
#define USE_ENCHANT 1
#endif

/* #undef HUNSPELL_FOUND */
#ifdef HUNSPELL_FOUND
#define USE_HUNSPELL 1
#endif

#define LYX_NLS 1
#ifdef LYX_NLS
#define ENABLE_NLS 1
// These are needed when building included gettext (taken from autoconf macro)
#define LYX_EXTERNAL_LIBINTL 1
#if !defined(LYX_EXTERNAL_LIBINTL)
// this only makes sense when LYX_EXTERNAL_LIBINTL is OFF.
#define __libc_lock_t                   gl_lock_t
#define __libc_lock_define              gl_lock_define
#define __libc_lock_define_initialized  gl_lock_define_initialized
#define __libc_lock_init                gl_lock_init
#define __libc_lock_lock                gl_lock_lock
#define __libc_lock_unlock              gl_lock_unlock
#define __libc_lock_recursive_t                   gl_recursive_lock_t
#define __libc_lock_define_recursive              gl_recursive_lock_define
#define __libc_lock_define_initialized_recursive  gl_recursive_lock_define_initialized
#define __libc_lock_init_recursive                gl_recursive_lock_init
#define __libc_lock_lock_recursive                gl_recursive_lock_lock
#define __libc_lock_unlock_recursive              gl_recursive_lock_unlock
#define glthread_in_use  libintl_thread_in_use
#define glthread_lock_init     libintl_lock_init
#define glthread_lock_lock     libintl_lock_lock
#define glthread_lock_unlock   libintl_lock_unlock
#define glthread_lock_destroy  libintl_lock_destroy
#define glthread_rwlock_init     libintl_rwlock_init
#define glthread_rwlock_rdlock   libintl_rwlock_rdlock
#define glthread_rwlock_wrlock   libintl_rwlock_wrlock
#define glthread_rwlock_unlock   libintl_rwlock_unlock
#define glthread_rwlock_destroy  libintl_rwlock_destroy
#define glthread_recursive_lock_init     libintl_recursive_lock_init
#define glthread_recursive_lock_lock     libintl_recursive_lock_lock
#define glthread_recursive_lock_unlock   libintl_recursive_lock_unlock
#define glthread_recursive_lock_destroy  libintl_recursive_lock_destroy
#define glthread_once                 libintl_once
#define glthread_once_call            libintl_once_call
#define glthread_once_singlethreaded  libintl_once_singlethreaded
#define hash_string			libintl_hash_string
#endif /* LYX_EXTERNAL_LIBINTL */
#endif


#endif // config.h guard



// Unguarded cleanup of global namespace:

#ifdef ColorMode
#undef ColorMode
#endif

#ifdef FocusOut
#undef FocusOut
#endif

#ifdef FocusIn
#undef FocusIn
#endif

#ifdef KeyRelease
#undef KeyRelease
#endif

#ifdef CursorShape
#undef CursorShape
#endif

#ifdef IGNORE
#undef IGNORE
#endif

#ifdef GrayScale
#undef GrayScale
#endif

#ifdef Status
#undef Status
#endif

#ifdef IN
#undef IN
#endif

#ifdef KeyPress
#undef KeyPress
#endif

