/*
 * \file configCompiler.h
 * This file is part of LyX, the document processor.
 * Licence details can be found in the file COPYING.
 *
 * This is the compilation configuration file for LyX.
 * It was generated by autoconfs configure.
 * You might want to change some of the defaults if something goes wrong
 * during the compilation.
 */

#ifndef _CONFIG_COMPILER_H
#define _CONFIG_COMPILER_H


#define HAVE_LIMITS_H 1
#define HAVE_LOCALE_H 1
#define HAVE_STDLIB_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_SYS_TYPES_H 1
/* #undef HAVE_SYS_UTIME_H */
#define HAVE_SYS_SOCKET_H 1
#define HAVE_UNISTD_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_UTIME_H 1
#define HAVE_STRING_H 1
/* #undef HAVE_ISTREAM */
/* #undef HAVE_OSTREAM */
/* #undef HAVE_IOS */
/* #undef HAVE_LOCALE */
#define HAVE_OPEN 1
#define HAVE_CHMOD 1
#define HAVE_CLOSE 1
#define HAVE_DCGETTEXT 1
#define HAVE_POPEN 1
#define HAVE_PCLOSE 1
/* #undef HAVE__OPEN */
/* #undef HAVE__CLOSE */
/* #undef HAVE__POPEN */
/* #undef HAVE__PCLOSE */
#define HAVE_GETPID 1
/* #undef HAVE__GETPID */
#define HAVE_GETTEXT 1
#define HAVE_MKDIR 1
/* #undef HAVE__MKDIR */
#define HAVE_PUTENV 1
#define HAVE_SETENV 1
#define HAVE_STRERROR 1
/* #undef HAVE_STD_COUNT */
/* #undef HAVE_ASPRINTF */
/* #undef HAVE_WPRINTF */
#define HAVE_SNPRINTF 1
#define HAVE_POSIX_PRINTF 1
#define HAVE_FCNTL 1
#define HAVE_INTMAX_T 1
/* #undef HAVE_INTTYPES_H_WITH_UINTMAX */
/* #undef CXX_GLOBAL_CSTD */
#define HAVE_GETCWD 1
#define HAVE_STPCPY 1
#define HAVE_STRCASECMP 1
#define HAVE_STRDUP 1
#define HAVE_STRTOUL 1
#define HAVE___FSETLOCKING 1
#define HAVE_MEMPCPY 1
#define HAVE___ARGZ_COUNT 1
#define HAVE___ARGZ_NEXT 1
#define HAVE___ARGZ_STRINGIFY 1
#define HAVE_SETLOCALE 1
#define HAVE_TSEARCH 1
#define HAVE_GETEGID 1
#define HAVE_GETGID 1
#define HAVE_GETUID 1
#define HAVE_WCSLEN 1
#define HAVE_MKFIFO 1
/* #undef HAVE_WPRINTF */
#define HAVE_LONG_DOUBLE 1
#define HAVE_LONG_LONG 1
#define HAVE_WCHAR_T 1
/* #undef HAVE_WINT_T */
/* #undef HAVE_STDINT_H_WITH_UINTMAX */
#define HAVE_LC_MESSAGES 1    
/* #undef HAVE_SSTREAM */
#define HAVE_ARGZ_H 1
/* #undef HAVE_MAGIC_H */
/* #undef SIZEOF_WCHAR_T_IS_2 */
#define SIZEOF_WCHAR_T_IS_4 1

#ifdef SIZEOF_WCHAR_T_IS_2
#  define SIZEOF_WCHAR_T 2
#else
#  ifdef SIZEOF_WCHAR_T_IS_4
#    define SIZEOF_WCHAR_T 4
#  endif
#endif

#define GETTEXT_FOUND 1

/* #undef HAVE_ALLOCA */
/* #undef HAVE_SYMBOL_ALLOCA */
#if defined(HAVE_SYMBOL_ALLOCA) && !defined(HAVE_ALLOCA)
#define HAVE_ALLOCA
#endif

/* #undef HAVE_ICONV_CONST */
#ifdef HAVE_ICONV_CONST
#define ICONV_CONST const
#else
#define ICONV_CONST
#endif

#ifdef _MSC_VER
#undef HAVE_OPEN  // use _open instead
#define pid_t int
#define PATH_MAX 512
#endif

#ifdef _WIN32 
#undef HAVE_MKDIR // use _mkdir instead
#endif

#define BOOST_ALL_NO_LIB 1

#if defined(HAVE_OSTREAM) && defined(HAVE_LOCALE) && defined(HAVE_SSTREAM)
#  define USE_BOOST_FORMAT 1
#else
#  define USE_BOOST_FORMAT 0
#endif

#ifdef _DEBUG
#  define ENABLE_ASSERTIONS 1
#endif

#ifndef ENABLE_ASSERTIONS
#  define BOOST_DISABLE_ASSERTS 1
#endif
#define BOOST_ENABLE_ASSERT_HANDLER 1

//#define BOOST_DISABLE_THREADS 1
#define BOOST_NO_WSTRING 1

#ifdef __CYGWIN__
#  define BOOST_POSIX 1
#  define BOOST_POSIX_API 1
#  define BOOST_POSIX_PATH 1
#endif

/*
 * the FreeBSD libc uses UCS4, but libstdc++ has no proper wchar_t
 * support compiled in:
 * http://gcc.gnu.org/onlinedocs/libstdc++/faq/index.html#3_9
 * And we are not interested at all what libc
 * does: What we need is a 32bit wide wchar_t, and a libstdc++ that
 * has the needed wchar_t support and uses UCS4. Whether it
 * implements this with the help of libc, or whether it has own code
 * does not matter for us, because we don't use libc directly (Georg)
*/
#if defined(HAVE_WCHAR_T) && SIZEOF_WCHAR_T == 4 && !defined(__FreeBSD__) && !defined(__FreeBSD_kernel__)
#  define USE_WCHAR_T
#endif

#if defined(MAKE_INTL_LIB) && defined(_MSC_VER)
#define __attribute__(x)
#define inline
#define uintmax_t UINT_MAX
#endif

#ifdef _MSC_VER
#ifdef HAVE_CHMOD
#undef HAVE_CHMOD
#endif
#endif

#ifdef HAVE_CHMOD
#define HAVE_MODE_T
#endif

/* #undef _GLIBCXX_DEBUG */
/* #undef _GLIBCXX_DEBUG_PEDANTIC */

#endif
